library(yaml)
source("../../../Library/CreatePlots.R", chdir=T)
source("../../../Library/PerformDatabaseOperations.R", chdir=T)
source("../../../Library/DocumentationModules.R", chdir=T)

config = yaml.load_file(g_config_path)
dir.create(file.path(normalize_directory_path(config$reporting$site_directory), "reports"), showWarnings = FALSE)
dir.create(file.path(normalize_directory_path(config$reporting$site_directory), "images"), showWarnings = FALSE)
source("./scripts/GeneratePersonReport.R", chdir=T)
source("./scripts/GenerateProviderReport.R", chdir=T)
source("./scripts/GenerateCare_SiteReport.R", chdir=T)
source("./scripts/GenerateOrganizationReport.R", chdir=T)
source("./scripts/GenerateLocationReport.R", chdir=T)
source("./scripts/GenerateDeathReport.R", chdir=T)
source("./scripts/GenerateVisit_OccurrenceReport_QueryWise.R", chdir=T)
source("./scripts/GenerateProcedure_OccurrenceReport_QueryWise.R", chdir=T)
source("./scripts/GenerateCondition_OccurrenceReport_QueryWise.R", chdir=T)
source("./scripts/GenerateObservationReport_QueryWise.R", chdir=T)
source("./scripts/GenerateObservation_PeriodReport.R", chdir=T)
